[pytest]

markers =
    divide_test: group of tests for divide function
    student_test: group of tests for Student class
    array_transformer:  group of tests for ArrayTransformer class
    smoke: used for smoke tests